"""Add seat_number column to epass table

Revision ID: 03ddd2fa52b8
Revises: 
Create Date: 2025-03-23 21:47:28.119392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ddd2fa52b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epass', schema=None) as batch_op:
        batch_op.drop_column('seat_number')

    # ### end Alembic commands ###
