"""Add SeatReservation model

Revision ID: be1b98aea6ec
Revises: a66d4e1fe296
Create Date: 2025-03-23 23:22:59.659808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1b98aea6ec'
down_revision = 'a66d4e1fe296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('payment_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.DATETIME(), nullable=False))
        batch_op.alter_column('payment_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
